### ISSUE TITLE
Get raw html/xml content

### ISSUE THREAD

**Issue by jakwings** [jakwings/macdict#4]
With the private APIs:

```
extern CFArrayRef DCSCopyRecordsForSearchString(DCSDictionaryRef dictionary, CFStringRef string, void *, void *);
extern CFStringRef DCSRecordCopyData(CFTypeRef record);
```

As illustrated by https://github.com/cdwind/mdict

**Comment by balta2ar** [comment]
@jakwings Do you think it's possible to dump the whole dictionary and export it? I'm learning Korean and I'd love to use two Korean dictionaries from iOS/macOS in GoldenDict, but I can't...

**Comment by iology** [comment]
@balta2ar Yeah, someone has done [some work](https://josephg.com/blog/reverse-engineering-apple-dictionaries/) to export the text part.

**Comment by iology** [comment]
solved in macdict2.m
